namespace ISCM.Domain.ValueObjects;

using ISCM.Domain.Enums;

/// <summary>
/// Phase 14.1: Immutable snapshot of environment capabilities.
/// Generated by IEnvironmentDetector.DetectEnvironmentAsync().
/// </summary>
public record EnvironmentProfile
{
    public required PermissionProfile Permissions { get; init; }
    public required ToolAvailabilityProfile AvailableTools { get; init; }
    public required PerformanceTier PerformanceTier { get; init; }
    public required IReadOnlyList<string> Warnings { get; init; }
    public required DateTimeOffset DetectedAt { get; init; }

    /// <summary>
    /// Hardware info captured during detection.
    /// </summary>
    public required HardwareProfile Hardware { get; init; }

    /// <summary>
    /// True if environment has all permissions and tools for a full scan.
    /// </summary>
    public bool IsFullyCapable =>
        Permissions.IsAdmin &&
        Permissions.CanReadRegistry &&
        AvailableTools.PowerShell &&
        AvailableTools.NetExe;

    /// <summary>
    /// True if any critical capability is missing that would prevent scan.
    /// </summary>
    public bool HasCriticalDeficiencies =>
        !Permissions.CanReadRegistry ||
        !AvailableTools.PowerShell;
}

public record PermissionProfile
{
    public required bool IsAdmin { get; init; }
    public required bool CanReadRegistry { get; init; }
    public required bool CanWriteRegistry { get; init; }
    public required bool CanRunSecedit { get; init; }
    public required bool CanRunPowerShell { get; init; }

    public bool HasAllPermissions =>
        IsAdmin && CanReadRegistry && CanWriteRegistry &&
        CanRunSecedit && CanRunPowerShell;
}

public record ToolAvailabilityProfile
{
    public required bool PowerShell { get; init; }
    public required string? PowerShellVersion { get; init; }
    public required bool NetExe { get; init; }
    public required bool Secedit { get; init; }
    public required bool Auditpol { get; init; }
}

public record HardwareProfile
{
    public required int ProcessorCount { get; init; }
    public required long TotalMemoryMB { get; init; }
    public required bool IsVirtualMachine { get; init; }
    public required string MachineName { get; init; }
}