using System;
using System.Collections.Generic;

namespace ISCM.BugFinder.Core.Models;

/// <summary>
/// BF-12.4: Ochiai-Specific Models
/// Extends standard localization models with Ochiai-specific metadata.
/// </summary>

/// <summary>
/// Detailed result for a single location using the Ochiai formula.
/// </summary>
public class OchiaiResult
{
    public string ElementId { get; set; } = string.Empty;
    public string FilePath { get; set; } = string.Empty;
    public int? LineNumber { get; set; }

    // The Core Score
    public double OchiaiScore { get; set; }

    // Rank among all analyzed elements
    public int Rank { get; set; }

    // Raw counters used for calculation (for auditability)
    public int FailedExecuted { get; set; }   // aef
    public int PassedExecuted { get; set; }   // aep
    public int TotalFailed { get; set; }      // F
    public int TotalPassed { get; set; }      // P

    // Diagnostic: How close is this to the next lower score? (Useful for tie-breaking analysis)
    public double ScoreMargin { get; set; }
}

/// <summary>
/// Full report generated by the Ochiai service.
/// </summary>
public class OchiaiLocalizationReport
{
    public List<OchiaiResult> RankedResults { get; set; } = new();
    public int TotalElementsAnalyzed { get; set; }
    public int TotalFailedTests { get; set; }
    public int TotalPassedTests { get; set; }

    // Top suspect summary
    public OchiaiResult? TopSuspect => RankedResults.Count > 0 ? RankedResults[0] : null;

    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
    public string WarningMessage { get; set; } = string.Empty;
}